version: '3.8'

services:
  api:
    build: .
    container_name: todolist-api-prod
    ports:
      - "8000:8000"
    volumes:
      - ./data:/code/data
    environment:
      - DATABASE_URL=sqlite:///./data/todolist_database.db
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
